### ISSUE TITLE
youku video  is  loss

### ISSUE THREAD

**Issue by TomatoBoy90** [taylorlu/voicepuppet#2]

**Comment by taylorlu** [comment]
Replaced by youtube link:
https://youtu.be/h24MGPTTw5M

**Comment by TomatoBoy90** [comment]
think you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DongLu"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午5:12
收件人: "taylorlu/voicepuppet"<voicepuppet@noreply.github.com&gt;; 
抄送: "介于ex与sinx的小朋友"<2548737967@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [taylorlu/voicepuppet] youku video  is  loss (#2)





 
Replaced by youtube link:
 https://youtu.be/h24MGPTTw5M
